[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'node-template'
publish = false
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'
version = '3.0.0-monthly-2021-08'
build = 'build.rs'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[[bin]]
name = 'node-template'
[build-dependencies.substrate-build-script-utils]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.node-template-runtime]
path = '../runtime'
version = '3.0.0-monthly-2021-08'

[dependencies]
jsonrpc-core = '15.1.0'
structopt = '0.3.8'

rand = "0.7.2"

sc-chain-spec = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-consensus-babe-rpc = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-consensus-epochs = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-consensus-slots = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-consensus-uncles = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-finality-grandpa-rpc = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-network = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-sync-state-rpc = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sp-authorship = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-keystore = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
pallet-im-online = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-mmr-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-staking = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }

beefy-primitives = { version = "0.1.0", git = "https://github.com/octopus-network/grandpa-bridge-gadget", branch = "dev" }
beefy-gadget = { version = "0.1.0", git = "https://github.com/octopus-network/grandpa-bridge-gadget", branch = "dev" }
beefy-gadget-rpc = { version = "0.1.0", git = "https://github.com/octopus-network/grandpa-bridge-gadget", branch = "dev" }

pallet-octopus-appchain = { git = "https://github.com/octopus-network/pallet-octopus-appchain", branch = "master" }

[dependencies.frame-benchmarking]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.1.0'

[dependencies.frame-benchmarking-cli]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.pallet-transaction-payment-rpc]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.sc-basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '0.9.0'

[dependencies.sc-cli]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '0.9.0'

[dependencies.sc-client-api]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.sc-consensus]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '0.9.0'

[dependencies.sc-consensus-babe]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '0.9.0'

[dependencies.sc-executor]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '0.9.0'

[dependencies.sc-finality-grandpa]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '0.9.0'

[dependencies.sc-keystore]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.sc-rpc]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.sc-rpc-api]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '0.9.0'

[dependencies.sc-service]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '0.9.0'

[dependencies.sc-telemetry]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.sc-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

# [dependencies.sc-transaction-pool-api]
# git = 'https://github.com/paritytech/substrate.git'
# tag = 'monthly-2021-08'
# version = '3.0.0'

[dependencies.sp-api]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.sp-block-builder]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.sp-blockchain]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.sp-consensus]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '0.9.0'

[dependencies.sp-consensus-babe]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '0.9.0'

[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.sp-finality-grandpa]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.sp-inherents]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.sp-timestamp]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[dependencies.substrate-frame-rpc-system]
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '3.0.0'

[features]
default = []
runtime-benchmarks = ['node-template-runtime/runtime-benchmarks']
